# Server Configuration
server:
  port: 8081
  address: 0.0.0.0

# Application
spring:
  application:
    name: beamlink-agent
  
  # File Upload
  servlet:
    multipart:
      enabled: true
      max-file-size: -1         # -1 = unlimited
      max-request-size: -1      # -1 = unlimited
      file-size-threshold: 0

# Agent Configuration
agent:
  nexus:
    url: http://localhost:5000
  name: ${COMPUTERNAME:Unknown-PC}
  upload:
    directory: ./received_files
  heartbeat:
    interval: 30000  # 30 seconds

# Logging
logging:
  level:
    root: INFO
    com.atamanahmet.beamlink: DEBUG
  file:
    name: agent.log